const registerRouter = require("./user.route")
const router = require("express").Router()
const productRouter = require("./product.route")
const aboutRouter = require("./about.router")
const phoneRouter = require("./phone.router")
const orderRouter = require("./order.router")
const PictureRouter = require("./picture.route")
const qobilyatRouter = require('./qobilyat.route')
router.use("/register", registerRouter)
router.use("/product",productRouter )
router.use("/about", aboutRouter)
router.use("/phone", phoneRouter)
router.use("/order", orderRouter)
router.use("/picture",PictureRouter)
router.use("/qobilyat",qobilyatRouter)
module.exports= router